{
  self,
  inputs,
  ...
}: {
  flake.nixosModules.homeserverModules = {
    pkgs,
    lib,
    config,
    ...
  }: let
    baseHomeModules = lib.attrValues self.homeModules;
    user = self.lib.users.mkUser {name = self.lib.usernames.homeserver;};
    host = self.lib.hosts.homeserver;
    sharedSystemPackages = import ../lib/system-packages.nix {inherit pkgs;};
    hostSpecificPackages = with pkgs; [
      openiscsi
      ollama
      helm
      mcrcon
      ripgrep
      systemd
      cifs-utils
      nfs-utils
      tmux
      jdk21_headless
    ];
  in {
    imports = [
      inputs.home-manager.nixosModules.default
      inputs.vscode-server.nixosModules.default
      self.nixosModules.homeserverHardware
    ];

    nix.settings.experimental-features = ["nix-command" "flakes"];
    nix.settings.trusted-users = host.trustedUsers;
    nix.settings.trusted-public-keys = [
      "cache.nixos.org-1:6NCHdD59X431o0gWypbMrAURkbJ16ZPMQFGspcDShjY="
    ];
    nix.settings.require-sigs = false; # 👈 easiest fix
    services.vscode-server.enable = true;

    boot.loader.grub.enable = true;
    boot.loader.grub.devices = ["nodev"];

    hardware.nvidia.open = true;

    services.k3s.enable = true;
    services.k3s.role = "server";
    services.k3s.token = builtins.getEnv "K3S_TOKEN";
    services.k3s.extraFlags = [
      "--write-kubeconfig-mode \"0644\""
      "--cluster-init"
      "--disable servicelb"
      "--disable traefik"
      "--disable local-storage"
    ];
    services.k3s.clusterInit = true;

    system.stateVersion = "26.05";

    environment.systemPackages = sharedSystemPackages ++ hostSpecificPackages;

    nixpkgs.config.allowUnfree = true;
    nixpkgs.config.permittedInsecurePackages = [
      "python-2.7.18.7"
      "python-2.7.18.12"
    ];

    networking.hostName = host.hostname;

    users.users.${user.username} = {
      isNormalUser = true;
      home = user.homeDirectory;
      description = "${user.username} user";
      extraGroups = [
        "wheel"
        "podman"
      ];
      openssh.authorizedKeys.keys = [
        # TODO: Move to secrets or environment variable
        "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIJcBI6f5YMyxp7CnRvR3gzpthbPOSZ8C390PNxlOT7Ql sonkusare.satish12@gmail.com"
        "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIMD16W2GHopl9X3e/RE8dBEbmgk8PPmnKTJQBGuihfkp sonkusare.satish12@gmail.com"
        "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIKbV6Jq6qkK3wOFLodNmUBys4vSzhAgBeIn2DcJR3ajw Generated By Termius"
      ];
    };

    programs.zsh.enable = true;
    programs.nix-ld.enable = true;

    virtualisation.containers.enable = true;

    virtualisation.podman = {
      enable = true;
      dockerCompat = true;
      defaultNetwork.settings.dns_enabled = true;
    };

    services.tailscale.enable = true;

    services.openssh = {
      enable = true;
      settings.PasswordAuthentication = false;
      settings.KbdInteractiveAuthentication = false;
      settings.PermitRootLogin = "yes";
    };

    networking.firewall = {
      enable = false;
      trustedInterfaces = ["tailscale0" "enp3s0"];
      allowedUDPPorts = [config.services.tailscale.port];
      allowedTCPPorts = [
        443
        22
        25565
        6443
        80
        11470
        3000
        8080
        3001
        6379
        3306
        11000
      ];
    };

    hardware.nvidia.modesetting.enable = true;
    hardware.nvidia-container-toolkit.enable = true;

    services.pipewire = {
      enable = true;
      alsa.enable = true;
      alsa.support32Bit = true;
      pulse.enable = true;
      jack.enable = true;
    };

    hardware.bluetooth = {
      enable = true;
      powerOnBoot = true;
    };
    services.blueman.enable = true;

    security.rtkit.enable = true;

    home-manager = {
      useGlobalPkgs = true;
      useUserPackages = true;

      extraSpecialArgs = {
        inherit inputs;
      };

      users.${user.username} = {
        imports = baseHomeModules;
        home = {
          username = user.username;
          homeDirectory = user.homeDirectory;
          stateVersion = "26.05";
        };

        programs.home-manager.enable = true;
      };
    };
  };
}
