{
  self,
  inputs,
  ...
}: let
  homeserverUsername = "teak";
  homeserverHomeDirectory = "/home/${homeserverUsername}";
in {
  flake.homeserverUser = {
    username = homeserverUsername;
    homeDirectory = homeserverHomeDirectory;
  };

  flake.nixosModules.homeserverModules = {
    pkgs,
    lib,
    config,
    ...
  }: let
    baseHomeModules = lib.attrValues self.homeModules;
  in {
    imports = [
      inputs.home-manager.nixosModules.default
      inputs.vscode-server.nixosModules.default
      self.nixosModules.homeserverHardware
    ];

    nix.settings.experimental-features = ["nix-command" "flakes"];
    # In your homeserver nixos config
    nix.settings.trusted-users = ["root" "teak" "anshsonkusare"];
    nix.settings.trusted-public-keys = [
      "cache.nixos.org-1:6NCHdD59X431o0gWypbMrAURkbJ16ZPMQFGspcDShjY="
    ];
    nix.settings.require-sigs = false; # 👈 easiest fix
    services.vscode-server.enable = true;

    boot.loader.grub.enable = true;
    boot.loader.grub.devices = ["nodev"];

    hardware.nvidia.open = true;

    services.k3s.enable = true;
    services.k3s.role = "server";
    services.k3s.token = "337f270011428199184147b7d66e2751a531dc0f2ba3a067455a79f0f4c46274";
    services.k3s.extraFlags = [
      "--write-kubeconfig-mode \"0644\""
      "--cluster-init"
      "--disable servicelb"
      "--disable traefik"
      "--disable local-storage"
    ];
    services.k3s.clusterInit = true;

    system.stateVersion = "25.11";

    environment.systemPackages = with pkgs; [
      pkgs.wget
      pkgs.tailscale
      pkgs.home-manager
      pkgs.kubectl
      openiscsi
      ollama
      helm
      mcrcon
      ripgrep
      systemd
      cifs-utils
      nfs-utils
      tmux
      jdk21_headless
    ];

    nixpkgs.config.allowUnfree = true;
    nixpkgs.config.permittedInsecurePackages = [
      "python-2.7.18.7"
      "python-2.7.18.12"
    ];

    fonts.packages = with pkgs; [
      noto-fonts
      noto-fonts-cjk-sans
      noto-fonts-color-emoji
      liberation_ttf
      fira-code
      fira-code-symbols
      mplus-outline-fonts.githubRelease
      dina-font
      proggyfonts
    ];

    networking.hostName = "homeserver";

    users.users.${homeserverUsername} = {
      isNormalUser = true;
      home = homeserverHomeDirectory;
      description = "${homeserverUsername} user";
      extraGroups = [
        "wheel"
        "podman"
      ];
      openssh.authorizedKeys.keys = [
        "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIJcBI6f5YMyxp7CnRvR3gzpthbPOSZ8C390PNxlOT7Ql sonkusare.satish12@gmail.com"
        "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIMD16W2GHopl9X3e/RE8dBEbmgk8PPmnKTJQBGuihfkp sonkusare.satish12@gmail.com"
        "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIKbV6Jq6qkK3wOFLodNmUBys4vSzhAgBeIn2DcJR3ajw Generated By Termius"
      ];
    };

    programs.zsh.enable = true;
    programs.nix-ld.enable = true;

    virtualisation.containers.enable = true;

    virtualisation.podman = {
      enable = true;
      dockerCompat = true;
      defaultNetwork.settings.dns_enabled = true;
    };

    services.tailscale.enable = true;

    services.openssh = {
      enable = true;
      settings.PasswordAuthentication = false;
      settings.KbdInteractiveAuthentication = false;
      settings.PermitRootLogin = "yes";
    };

    networking.firewall = {
      enable = false;
      trustedInterfaces = ["tailscale0" "enp3s0"];
      allowedUDPPorts = [config.services.tailscale.port];
      allowedTCPPorts = [
        443
        22
        25565
        6443
        80
        11470
        3000
        8080
        3001
        6379
        3306
        11000
      ];
    };

    hardware.nvidia.modesetting.enable = true;
    hardware.nvidia-container-toolkit.enable = true;

    services.pipewire = {
      enable = true;
      alsa.enable = true;
      alsa.support32Bit = true;
      pulse.enable = true;
      jack.enable = true;
    };

    hardware.bluetooth = {
      enable = true;
      powerOnBoot = true;
    };
    services.blueman.enable = true;

    security.rtkit.enable = true;

    home-manager = {
      useGlobalPkgs = true;
      useUserPackages = true;

      extraSpecialArgs = {
        inherit inputs;
      };

      users.${homeserverUsername} = {
        imports = baseHomeModules;
        home = {
          username = homeserverUsername;
          homeDirectory = homeserverHomeDirectory;
          stateVersion = "25.11";
        };

        programs.home-manager.enable = true;
        services.ssh-agent.enable = true;
      };
    };
  };
}
